!!python/object:__main__.Config
accum_iter: 1
add_w: origin
attn_mode: normal
batch_size: 20
blr: 0.01
clip_grad: null
cls_token: false
config: 'E:/recherche/brain/brain-jepa\Brain-JEPA-main/Brain-JEPA-main/configs/downstream/fine_tune.yaml '
crop_size: !!python/tuple
- 450
- 160
data_make_fn: hca_sex
device: cpu
downsample: false
downstream_task: lin_probe
drop_path: 0.1
epochs: 20
eval: false
finetune: downstream_tasks\jepa-ep300.pth.tar
global_pool: true
gradient_checkpointing: false
label_normalization: false
layer_decay: 0.75
load_epoch: '300'
load_path: downstream_tasks
local_rank: -1
log_dir: hca_sex\lin_probe_classification\jepa-ep300_2024-12-09_13-14-45\ft_log
lr: null
min_lr: 1.0e-06
model_name: vit_base
nb_classes: 2
no_pin_mem: false
num_seed: 5
num_workers: 8
output_dir: hca_sex\lin_probe_classification\jepa-ep300_2024-12-09_13-14-45\ft_output
output_root: ''
patch_size: 16
pin_mem: true
pred_depth: 12
pred_emb_dim: 384
resume: ''
seed: 0
smoothing: 0.0
start_epoch: 0
task: classification
use_normalization: false
warmup_epochs: 0
weight_decay: 0.05
world_size: 1
